CREATE TABLE DIARY (
	DIARY_NO NUMBER CONSTRAINT TB_DIARY_PK PRIMARY KEY,
	DIARY_TITLE VARCHAR2(50) NOT NULL,
	DIARY_WEATHER VARCHAR2(50),
	DIARY_FEEL VARCHAR2(50),
	DIARY_CONTENT VARCHAR2(4000) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE
	);
	
COMMENT ON COLUMN DIARY.DIARY_NO IS '일기 번호';
COMMENT ON COLUMN DIARY.DIARY_TITLE IS '일기 제목';
COMMENT ON COLUMN DIARY.DIARY_WEATHER IS '날씨';
COMMENT ON COLUMN DIARY.DIARY_FEEL IS  '기분';
COMMENT ON COLUMN DIARY.DIARY_CONTENT IS '일기 내용';
COMMENT ON COLUMN DIARY.REG_DATE IS '일기 등록일';

--일기 번호(DIARY_NO) 번호 생성기(SEQUENCE) 만들기
CREATE SEQUENCE SEQ_DIARY_NO NOCACHE;

--샘플 데이터 추가
INSERT INTO DIARY
VALUES(SEQ_DIARY_NO.NEXTVAL, '일기 제목1','날씨 좋음','기분 좋음', '일기 내용1',DEFAULT);
INSERT INTO DIARY
VALUES(SEQ_DIARY_NO.NEXTVAL, '일기 제목2','날씨 보통','기분 좋음', '일기 내용2',DEFAULT);
INSERT INTO DIARY
VALUES(SEQ_DIARY_NO.NEXTVAL, '일기 제목3','날씨 나쁨','기분 좋음', '일기 내용3',DEFAULT);

-- 전체 조회
SELECT * FROM DIARY;

SELECT * FROM DIARY
ORDER BY DIARY_NO;

DELETE FROM DIARY
WHERE DIARY_TITLE='qwer';

SELECT * 
FROM DIARY
WHERE DIARY_NO =;


DROP SEQUENCE SEQ_DIARY_NO;
CREATE SEQUENCE SEQ_DIARY_NO 
START WITH 7
NOCACHE;

